# This message contains robot HP data received from the referee system

std_msgs/Header header

# red team
uint16 red_1_robot_hp
uint16 red_2_robot_hp
uint16 red_3_robot_hp
uint16 red_4_robot_hp
uint16 red_5_robot_hp
uint16 red_7_robot_hp
uint16 red_outpost_hp
uint16 red_base_hp

# blue team
uint16 blue_1_robot_hp
uint16 blue_2_robot_hp
uint16 blue_3_robot_hp
uint16 blue_4_robot_hp
uint16 blue_5_robot_hp
uint16 blue_7_robot_hp
uint16 blue_outpost_hp
uint16 blue_base_hp